version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
    ports:
      - "5432"
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
      - ./script/docker/config/database.yml:/app/config/database.yml
    ports:
      - "3000:3000"
    depends_on:
      - db
